# Series Data Collection 

## Objective

The objective of this notebook is to collect information on series adaptations from Amazon Prime Video and Netflix and enrich the dataset with IMDb metadata for further analysis.

## Data Sources

* Wikipedia pages containing lists of Netflix/Amazon original titles.
* OMDb API for IMDb metadata such as ratings, vote counts, genres, release years, and content ratings.

## Methodology

1. Titles were collected through web scraping from Wikipedia.
2. IMDb metadata was retrieved using the OMDb API.
3. Each title was manually verified to determine whether it was based on a book.
4. Only confirmed book adaptations were retained for further analysis.

# Amazon Series Data Collection

## Web Scraping Wikipedia Data

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_Amazon_Prime_Video_original_programming"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

In [3]:
from io import StringIO

tables = pd.read_html(StringIO(html))

print(len(tables))

87

In [4]:
for i, table in enumerate(tables):
    print(f"\nTABLE {i}")
    print(table.head())

TABLE 0
                                       Title         Genre           Premiere  \
0                                    Reacher   Crime drama   February 4, 2022
1                          The Terminal List  Action drama       July 1, 2022
2  The Lord of the Rings: The Rings of Power       Fantasy  September 1, 2022
3                           The Devil's Hour      Thriller   October 28, 2022
4                                    Citadel     Spy drama     April 28, 2023

                  Seasons                                             Status
0  3 seasons, 24 episodes                      Renewed for seasons 4–5[2][3]
1    1 season, 8 episodes  Season 2 due to premiere on October 21, 2026[4...
2  2 seasons, 16 episodes  Season 3 due to premiere on November 11, 2026[...
3  2 seasons, 11 episodes                                         Renewed[8]
4  2 seasons, 13 episodes                                            Pending

TABLE 1
              Title             Genre          Premiere  \
0          Deadloch            Comedy      June 2, 2023
1  Mr. & Mrs. Smith        Spy comedy  February 2, 2024
2  Overcompensating            Comedy      May 15, 2025
3              Bait            Comedy    March 25, 2026
4  Awaiting release  Awaiting release  Awaiting release

                  Seasons            Status
0  2 seasons, 14 episodes           Pending
1    1 season, 8 episodes       Renewed[18]
2    1 season, 8 episodes       Renewed[19]
3    1 season, 6 episodes           Pending
4        Awaiting release  Awaiting release

TABLE 2
                       Title                 Genre          Premiere  \
0                 Invincible       Superhero drama    March 25, 2021
1  The Legend of Vox Machina        Fantasy action  January 28, 2022
2               Hazbin Hotel  Musical black comedy  January 19, 2024
3   Sausage Party: Foodtopia                Comedy     July 11, 2024
4     Batman: Caped Crusader             Superhero    August 1, 2024

                  Seasons                                             Status
0  4 seasons, 33 episodes                                        Renewed[27]
1  4 seasons, 48 episodes      Season 4 ongoing Renewed for final season[28]
2  2 seasons, 16 episodes            Renewed for seasons 3–5 (final)[29][30]
3  2 seasons, 16 episodes                                            Pending
4   1 season, 10 episodes  Season 2 due to premiere on July 31, 2026[31][32]

TABLE 3
                    Title      Genre          Premiere               Seasons  \
0  Tatsuki Fujimoto 17-26  Anthology  November 7, 2025  1 season, 8 episodes

    Status
0  Pending

TABLE 4
                   Title                Genre           Premiere  \
0  The Chosen Adventures  Christian adventure   October 17, 2025
1                Bat-Fam     Superhero comedy  November 10, 2025

                 Seasons   Status
0  1 season, 14 episodes  Pending
1  1 season, 10 episodes  Pending

TABLE 5
                  Title                Genre          Premiere  \
0             The Alibi    Romantic thriller  November 7, 2025
1    Love Is Never Gone       Romantic drama       May 8, 2026
2      Awaiting release     Awaiting release  Awaiting release
3  The Loyalty Game[35]  Psychological drama  July 3, 2026[36]

                 Seasons            Status
0  1 season, 14 episodes           Pending
1  1 season, 14 episodes           Pending
2       Awaiting release  Awaiting release
3                    TBA           Pending

TABLE 6
             Title                       Genre           Premiere  \
0      Escort Boys                Comedy drama  December 22, 2023
1            Culte  Historical drama anthology   October 18, 2024
2  The Glass House                Comedy drama        May 1, 2026

                  Seasons   Status
0  2 seasons, 12 episodes  Pending
1  2 seasons, 12 episodes  Pending
2    1 season, 6 episodes  Pending

TABLE 7
               Title                        Genre            Premiere  \
0     The Family Man                 Spy thriller  September 20, 2019
1          Panchayat                 Comedy drama       April 3, 2020
2             Tandav           Political thriller    January 15, 2021
3              Farzi  Black comedy crime thriller   February 10, 2023
4  Sapne Vs Everyone                        Drama    December 8, 2023

                  Seasons       Status
0  3 seasons, 26 episodes      Pending
1  4 seasons, 32 episodes  Renewed[37]
2    1 season, 9 episodes  Renewed[38]
3    1 season, 8 episodes  Renewed[39]
4  2 seasons, 10 episodes      Pending

TABLE 8
                Title                        Genre          Premiere  \
0  The Silent Service  Military political thriller  February 9, 2024
1    Awaiting release             Awaiting release  Awaiting release
2       Hanzaisha[44]               Crime thriller     July 17, 2026

                  Seasons            Status
0  2 seasons, 16 episodes       Renewed[43]
1        Awaiting release  Awaiting release
2                     TBA           Pending

TABLE 9
                                Title            Genre           Premiere  \
0                      Club Hooligans     Sports drama      June 23, 2023
1                           Red Queen   Crime thriller  February 29, 2024
2  Betty, la fea: The Story Continues  Romantic comedy      July 19, 2024
3                 Every Minute Counts            Drama   November 8, 2024
4                         Her Majesty           Comedy  February 27, 2025

                  Seasons                       Status
0  2 seasons, 16 episodes                      Pending
1    1 season, 7 episodes  Renewed for seasons 2–3[45]
2  2 seasons, 20 episodes                  Renewed[46]
3  2 seasons, 20 episodes                      Pending
4    1 season, 7 episodes                  Renewed[47]

TABLE 10
                              Title           Genre           Premiere  \
0                       New Bandits     Crime drama    August 18, 2023
1                   That Cover Girl  Romantic drama   October 19, 2023
2       Fading Gigolo: The Sex Guru          Comedy  December 21, 2023
3  Maxton Hall—The World Between Us      Teen drama        May 9, 2024
4                     Arabia Kadali  Suspense drama     August 8, 2025

                  Seasons    Language       Status
0  2 seasons, 15 episodes  Portuguese      Pending
1    1 season, 6 episodes       Malay  Renewed[49]
2  2 seasons, 12 episodes     Italian      Pending
3  2 seasons, 12 episodes      German  Renewed[50]
4    1 season, 8 episodes      Telugu      Pending

TABLE 11
                      Title                              Subject  \
0            The Grand Tour                             Motoring
1           Clarkson's Farm                          Agriculture
2        Shiny Happy People  Religious fundamentalism/True crime
3   Faceoff: Inside the NHL                               Sports
4  Molly-Mae: Behind It All                  Celebrity/Lifestyle

            Premiere                 Seasons Language  \
0  November 18, 2016  6 seasons, 46 episodes  English
1      June 11, 2021  5 seasons, 40 episodes  English
2       June 2, 2023   2 seasons, 7 episodes  English
3    October 4, 2024  2 seasons, 12 episodes  English
4   January 17, 2025  2 seasons, 12 episodes  English

                                 Status
0  Season 7 due to premiere in 2026[51]
1                               Pending
2                               Pending
3                               Pending
4                               Pending

TABLE 12
                            Title                        Genre  \
0    LOL: Last One Laughing Italy  Stand-up comedy competition
1  LOL: Last One Laughing Germany  Stand-up comedy competition
2             LOL: Qui rit, sort!  Stand-up comedy competition
3   LOL: Last One Laughing Brazil  Stand-up comedy competition
4   LOL: Last One Laughing Quebec  Stand-up comedy competition

            Premiere                 Seasons    Language       Status
0  February 26, 2021  6 seasons, 37 episodes     Italian      Pending
1      April 1, 2021  6 seasons, 37 episodes      German      Pending
2     April 22, 2021  6 seasons, 39 episodes      French      Pending
3   December 3, 2021  5 seasons, 30 episodes  Portuguese      Pending
4    January 6, 2023  4 seasons, 24 episodes      French  Renewed[54]

TABLE 13
                                            Title                   Genre  \
0                                     Dish It Out  Cooking show/Talk show
1  Good Sports with Kevin Hart and Kenan Thompson        Sports talk show

            Premiere                Seasons Language   Status
0  September 5, 2025  1 season, 32 episodes  English  Pending
1  November 25, 2025  1 season, 12 episodes  English  Pending

TABLE 14
                       Title                        Genre  Partner  \
0                Spider-Noir               Superhero noir     MGM+
1  Sidemen Present: SideMenu  Cooking reality competition  YouTube

        Premiere               Seasons Language            Status
0   May 27, 2026  1 season, 8 episodes  English           Pending
1  June 19, 2026  1 season, 4 episodes  English  Season 1 ongoing

TABLE 15
                            Title                                 Genre  \
0  Tribunal Justice (seasons 2–3)  Arbitration-based reality court show
1         Judy Justice (season 4)  Arbitration-based reality court show
2            Jury Duty (season 2)                          Mockumentary

  Prev. network(s)          Premiere                  Seasons Language  \
0   Amazon Freevee  January 27, 2025  2 seasons, 160 episodes  English
1   Amazon Freevee  January 19, 2026   1 season, 120 episodes  English
2   Amazon Freevee    March 20, 2026     1 season, 8 episodes  English

             Status
0  Season 3 ongoing
1  Season 4 ongoing
2       Renewed[63]

TABLE 16
          Title               Genre          Premiere                 Seasons  \
0    Punto Nemo              Action    March 28, 2025  2 seasons, 10 episodes
1  Snake Killer      Crime thriller  January 15, 2026    1 season, 4 episodes
2          Vaka  Dystopian thriller  January 30, 2026    1 season, 6 episodes

  Prime Video exclusive region Language   Status
0                        Spain  Spanish  Pending
1                      Nordics   Danish  Pending
2                      Nordics  Swedish  Pending

TABLE 17
                                               Title                    Genre  \
0  Pesci piccoli – Un'agenzia, molte idee, poco b...         Workplace comedy
1                                In the Name of Love  Historical comedy drama
2                                        Top End Bub          Romantic comedy

             Premiere                 Seasons Prime Video exclusive region  \
0        June 8, 2023  2 seasons, 14 episodes                        Italy
1   September 5, 2025    1 season, 8 episodes                      Nordics
2  September 12, 2025    1 season, 8 episodes    Australia and New Zealand

  Language   Status
0  Italian  Pending
1   Norway  Pending
2  English  Pending

TABLE 18
                           Title                 Genre           Premiere  \
0  Spice of Life med Stian Blipp            Prank show  December 16, 2022
1                  Girls of Oslo             Docu-soap   November 3, 2023
2                         The 50  Survival competition     March 11, 2024
3            The Traitors Italia   Reality competition   October 30, 2025
4                   Karaoké Club   Reality competition  November 21, 2025

                  Seasons Prime Video exclusive region   Language       Status
0    1 season, 6 episodes                       Norway  Norwegian  Renewed[64]
1  3 seasons, 18 episodes                       Norway  Norwegian      Pending
2  3 seasons, 45 episodes          Austria and Germany     German      Pending
3    1 season, 6 episodes                        Italy    Italian  Renewed[65]
4    1 season, 6 episodes                       Canada     French      Pending

TABLE 19
                     Title         Genre         Premiere  \
0  R.I.P. – Roast in Peace  Roast comedy  October 9, 2025

                Seasons Prime Video exclusive region Language   Status
0  1 season, 6 episodes                        Italy  Italian  Pending

TABLE 20
                               Title         Genre            Partner/Country  \
0  La que se avecina (seasons 12–16)        Sitcom            Telecinco/Spain
1                       The Assassin      Thriller  Stan/AustraliaZDF/Germany
2    The Night Manager (season 2)[d]  Spy thriller     BBC One/United Kingdom

           Premiere                 Seasons Prime Video exclusive region  \
0      May 29, 2020  5 seasons, 48 episodes                        Spain
1     July 25, 2025    1 season, 6 episodes               United Kingdom
2  January 11, 2026    1 season, 6 episodes            All other markets

  Language       Status
0  Spanish  Renewed[66]
1  English  Renewed[67]
2  English  Renewed[68]

TABLE 21
                           Title                Genre  \
0  Operación Triunfo (season 12)  Reality competition

                                  Prev. network(s)           Premiere  \
0  La 1 (seasons 1–3; 9–11)Telecinco (seasons 4–8)  November 20, 2023

                  Seasons Prime Video exclusive region Language       Status
0  2 seasons, 28 episodes                        Spain  Spanish  Renewed[69]

TABLE 22
                       Title                       Genre          Premiere  \
0                 Carrie[70]         Supernatural horror  October 2026[71]
1       The Greatest[72][73]    Sports biopic miniseries     Late 2026[74]
2            Kill Jackie[75]             Action thriller          2026[76]
3               Bloodaxe[77]            Historical drama    Early 2027[78]
4  Blade Runner 2099[79][80]  Science fiction miniseries          2027[81]

                Seasons
0  1 season, 8 episodes
1            8 episodes
2  1 season, 8 episodes
3         2 seasons[78]
4                   TBA

TABLE 23
                                               Title               Genre  \
0                     Postcards from Italy[116][117]              Comedy
1                                    Barbershop[119]    Workplace comedy
2                                      Escorted[120]     Romantic comedy
3  Untitled Totally Spies! live-action adaptation...  Young adult action

    Premiere               Seasons
0  2026[118]                   TBA
1        TBA                   TBA
2        TBA  1 season, 8 episodes
3        TBA                   TBA

TABLE 24
               Title                   Genre Premiere Seasons
0  Lore Olympus[122]         Fantasy romance      TBA     TBA
1      Odd Jobs[123]  Science fiction comedy      TBA     TBA
2       Wytches[124]     Supernatural horror      TBA     TBA

TABLE 25
                         Title                                          Genre  \
0  Fist of the North Star[125]  Adventure martial arts post-apocalyptic drama

   Premiere Seasons  Language
0      2026     TBA  Japanese

TABLE 26
                            Title                              Genre Premiere  \
0          Cupcake & Friends[126]                     Fantasy comedy      TBA
1  Love, Diana Music Hunters[126]  Science fiction musical adventure      TBA

  Seasons
0     TBA
1     TBA

TABLE 27
                     Title               Genre             Premiere Seasons
0     Honor Thy Mother[35]        Family drama  September 2026[127]     TBA
1               Kopino[35]      Romantic drama   November 2026[128]     TBA
2  Behind Closed Doors[35]  Political thriller                 2026     TBA

TABLE 28
                        Title             Genre Premiere Seasons
0  The Great Indian Code[129]  Historical drama      TBA     TBA
1         Gulkanda Tales[129]      Comedy drama      TBA     TBA
2    The Revolutionaries[129]  Historical drama      TBA     TBA

TABLE 29
                      Title                Genre Premiere  \
0   Murder in the Dark[130]          Crime drama     2026
1            El juicio[131]          Crime drama      TBA
2         Game of Keys[132]               Comedy      TBA
3  Gangs Kuruthi Punal[129]  Period action drama      TBA
4       Glamsquad[133][134]         Comedy drama      TBA

                Seasons Language
0  1 season, 6 episodes   Danish
1                   TBA  Spanish
2                   TBA   German
3                   TBA    Tamil
4                   TBA   French

TABLE 30
                                    Title  \
0                     Hometown Giants[54]
1        Pelayo. Más allá del límite[135]
2  All or Nothing: Manchester United[136]
3                 Operation Deception[54]
4      The Pig Farmer: Robert Pickton[54]

                                          Subject   Premiere     Seasons  \
0                                          Sports  Late 2026         TBA
1  Investigative journalism/True crime miniseries       2026  3 episodes
2                                          Sports   Mid-2027         TBA
3                                      True crime        TBA  2 episodes
4                                      True crime        TBA  3 episodes

  Language
0  English
1  Spanish
2  English
3   French
4  English

TABLE 31
                   Title              Subject Premiere                Seasons  \
0   Reality Retreat[137]         Docu-reality     2027                    TBA
1   Fallout Shelter[138]  Reality competition      TBA  1 season, 10 episodes
2   Heels in the Hay[54]         Docu-reality      TBA                    TBA
3  Kaleb Down Under[139]              Reality      TBA   1 season, 4 episodes
4          Surrender[54]  Reality competition      TBA                    TBA

  Language
0  English
1  English
2   French
3  English
4  English

TABLE 32
                                Title                 Genre  \
0  Helluva Boss (seasons 3–4)[e][140]  Musical black comedy
1                     Anaon[134][142]      Fantasy thriller

                      Partner   Premiere                Seasons Language
0  SpindleHorse/United States  2026[141]  1 season, 15 episodes  English
1   France Télévisions/France        TBA                    TBA   French

TABLE 33
                                 Title                   Genre
0                       Bloodlust[143]             Dark comedy
1  Blue Mountain State (season 4)[144]                  Sitcom
2                   The Boyfriend[145]  Psychological thriller
3            The Boys from Biloxi[146]             Crime drama
4            The Boys: Mexico[147][83]         Superhero drama

TABLE 34
  vteList of television programs broadcast by region  \
0  Asia-wide Animal Planet Animax Armenia TV AXN ...
1                                          Asia-wide
2  Animal Planet Animax Armenia TV AXN BBC Boomer...
3  East AsiaHong Kong TVB ViuTVsix Star Vijay Jap...
4                                          East Asia

  vteList of television programs broadcast by region.1
0  Asia-wide Animal Planet Animax Armenia TV AXN ...
1                                          Asia-wide
2  Animal Planet Animax Armenia TV AXN BBC Boomer...
3  East AsiaHong Kong TVB ViuTVsix Star Vijay Jap...
4                                          East Asia

TABLE 35
                                           Asia-wide  \
0  Animal Planet Animax Armenia TV AXN BBC Boomer...

                                         Asia-wide.1
0  Animal Planet Animax Armenia TV AXN BBC Boomer...

TABLE 36
                                           East Asia  \
0  Hong Kong TVB ViuTVsix Star Vijay Japan Animax...
1                                          Hong Kong
2                                              Japan
3                                        South Korea

                                         East Asia.1
0  Hong Kong TVB ViuTVsix Star Vijay Japan Animax...
1                            TVB ViuTVsix Star Vijay
2                       Animax TBS Tokyo MX TV Tokyo

In [5]:
dfs = []

for table in tables:
    if "Title" in table.columns:
        dfs.append(table)

amazon_df = pd.concat(dfs, ignore_index=True)

amazon_df.drop_duplicates(subset=["Title"], inplace=True)

print(amazon_df.head())
print(len(amazon_df))

                                       Title         Genre           Premiere  \
0                                    Reacher   Crime drama   February 4, 2022
1                          The Terminal List  Action drama       July 1, 2022
2  The Lord of the Rings: The Rings of Power       Fantasy  September 1, 2022
3                           The Devil's Hour      Thriller   October 28, 2022
4                                    Citadel     Spy drama     April 28, 2023

                  Seasons                                             Status  \
0  3 seasons, 24 episodes                      Renewed for seasons 4–5[2][3]
1    1 season, 8 episodes  Season 2 due to premiere on October 21, 2026[4...
2  2 seasons, 16 episodes  Season 3 due to premiere on November 11, 2026[...
3  2 seasons, 11 episodes                                         Renewed[8]
4  2 seasons, 13 episodes                                            Pending

  Language Subject Partner Prev. network(s) Prime Video exclusive region  \
0      NaN     NaN     NaN              NaN                          NaN
1      NaN     NaN     NaN              NaN                          NaN
2      NaN     NaN     NaN              NaN                          NaN
3      NaN     NaN     NaN              NaN                          NaN
4      NaN     NaN     NaN              NaN                          NaN

  Partner/Country
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
264

In [6]:
amazon_df.info()

<class 'pandas.DataFrame'>
Index: 264 entries, 0 to 268
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Title                         264 non-null    str
 1   Genre                         245 non-null    str
 2   Premiere                      207 non-null    object
 3   Seasons                       207 non-null    str
 4   Status                        141 non-null    str
 5   Language                      83 non-null     str
 6   Subject                       19 non-null     str
 7   Partner                       4 non-null      str
 8   Prev. network(s)              4 non-null      str
 9   Prime Video exclusive region  16 non-null     str
 10  Partner/Country               3 non-null      str
dtypes: object(1), str(10)
memory usage: 24.8+ KB

In [7]:
amazon_df = amazon_df[["Title", "Premiere"]]

In [8]:
amazon_df.info()

<class 'pandas.DataFrame'>
Index: 264 entries, 0 to 268
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     264 non-null    str
 1   Premiere  207 non-null    object
dtypes: object(1), str(1)
memory usage: 6.2+ KB

In [9]:
print(amazon_df["Title"].duplicated().sum())

0

In [10]:
amazon_df.sample(n=10, random_state=42)

                                    Title           Premiere
71                   Mentiras, The Series      June 13, 2025
199                   Glamsquad[133][134]                TBA
85                        Clarkson's Farm      June 11, 2021
252                           She-Ra[176]                NaN
113                    LOL: In Real Life!  November 21, 2025
123                           Dish It Out  September 5, 2025
117                   American Gladiators     April 17, 2026
183                     Lore Olympus[122]                TBA
9                                 Ballard       July 9, 2025
256  Taylor Lautner: Werewolf Hunter[180]                NaN

In [11]:
amazon_df['Title'] = amazon_df['Title'].str.replace(r'\[\d+\]', '', regex=True).str.strip()
amazon_df['Premiere'] = amazon_df['Premiere'].str.replace(r'\[\d+\]', '', regex=True).str.strip()

In [12]:
amazon_df["Title"] = (amazon_df["Title"].str.replace(r"\[[a-z]\]", "", regex=True).str.strip())

In [13]:
amazon_df[amazon_df["Title"].str.contains(r"\[", regex=True, na=False)]

Empty DataFrame
Columns: [Title, Premiere]
Index: []

In [14]:
amazon_df.sample(n=10, random_state=42)

                               Title           Premiere
71              Mentiras, The Series      June 13, 2025
199                        Glamsquad                TBA
85                   Clarkson's Farm      June 11, 2021
252                           She-Ra                NaN
113               LOL: In Real Life!  November 21, 2025
123                      Dish It Out  September 5, 2025
117              American Gladiators     April 17, 2026
183                     Lore Olympus                TBA
9                            Ballard       July 9, 2025
256  Taylor Lautner: Werewolf Hunter                NaN

In [15]:
amazon_df['Premiere'] = pd.to_datetime(amazon_df['Premiere'],errors='coerce')

In [16]:
cutoff_date = pd.Timestamp('2026-06-18')

In [17]:
premiered_df = amazon_df[(amazon_df['Premiere'].notna()) & (amazon_df['Premiere'] < cutoff_date)].copy()

premiered_df.to_csv('../data/series/raw/amazon_titles.csv', index=False)

In [18]:
upcoming_tba_df = amazon_df[(amazon_df['Premiere'].isna()) | (amazon_df['Premiere'] >= cutoff_date)].copy()

upcoming_tba_df.to_csv('../data/series/raw/upcoming_amazon.csv', index=False)

In [19]:
print(f"Premiered titles: {len(premiered_df)}")
print(f"Upcoming/TBA titles: {len(upcoming_tba_df)}")

Premiered titles: 128
Upcoming/TBA titles: 136

## Retrieving IMDb Metadata

In [20]:
import requests

API_KEY = "adebd275"

title = "Reacher"

url = f"https://www.omdbapi.com/?t={title}&apikey={API_KEY}"

response = requests.get(url)

data = response.json()

print(data)

{'Title': 'Reacher', 'Year': '2022–', 'Rated': 'TV-MA', 'Released': '04 Feb 2022', 'Runtime': '1 min', 'Genre': 'Action, Crime, Drama', 'Director': 'N/A', 'Writer': 'Nick Santora', 'Actors': 'Alan Ritchson, Maria Sten, Malcolm Goodwin', 'Plot': 'Itinerant former military policeman Jack Reacher solves crimes and metes out his own brand of street justice. Based on the novels by Lee Child.', 'Language': 'English', 'Country': 'United States', 'Awards': '3 wins & 13 nominations total', 'Poster': 'https://m.media-amazon.com/images/M/MV5BMzdjYWZlMDQtYzdhNi00NmRlLTg2NzUtMTI3MWFhZDliNjBiXkEyXkFqcGc@._V1_QL75_UX380_CR0,57,380,562_.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'}], 'Metascore': 'N/A', 'imdbRating': '8.0', 'imdbVotes': '291,841', 'imdbID': 'tt9288030', 'Type': 'series', 'totalSeasons': '4', 'Response': 'True'}

In [21]:
def get_omdb_data(title):

    try:
        url = f"https://www.omdbapi.com/?t={title}&apikey={API_KEY}"

        data = requests.get(url).json()

        return pd.Series({
            "Rated": data.get("Rated"),
            "imdb_rating": data.get("imdbRating"),
            "imdb_votes": data.get("imdbVotes"),
            "imdb_genre": data.get("Genre"),
            "imdb_year": data.get("Year"),
            "imdb_type": data.get("Type")
        })

    except:
        return pd.Series()

In [22]:
amazon_df = pd.read_csv('../data/series/raw/amazon_titles.csv')

In [23]:
omdb_data = amazon_df["Title"].apply(get_omdb_data)

amazon_df = pd.concat(
    [amazon_df, omdb_data],
    axis=1
)

In [24]:
amazon_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        128 non-null    str
 1   Premiere     128 non-null    str
 2   Rated        109 non-null    str
 3   imdb_rating  109 non-null    str
 4   imdb_votes   109 non-null    str
 5   imdb_genre   109 non-null    str
 6   imdb_year    109 non-null    str
 7   imdb_type    109 non-null    str
dtypes: str(8)
memory usage: 8.1 KB

In [25]:
amazon_df.head()

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type
0,Reacher,2022-02-04,TV-MA,8.0,"291,841","Action, Crime, Drama",2022–,series
1,The Terminal List,2022-07-01,TV-MA,7.9,"127,044","Action, Drama, Thriller",2022–,series
2,The Lord of the Rings: The Rings of Power,2022-09-01,TV-14,6.9,"436,113","Action, Adventure, Drama",2022–,series
3,The Devil's Hour,2022-10-28,TV-MA,7.6,"32,008","Drama, Mystery, Thriller",2022–,series
4,Citadel,2023-04-28,TV-14,6.2,"37,316","Action, Drama, Thriller",2023–,series

In [26]:
amazon_df['imdb_votes'] = (amazon_df['imdb_votes'].astype(str).str.replace(',', '', regex=False))

In [27]:
amazon_df['imdb_rating'] = pd.to_numeric(amazon_df['imdb_rating'], errors='coerce')
amazon_df['imdb_votes'] = pd.to_numeric(amazon_df['imdb_votes'], errors='coerce')

In [28]:
amazon_df['imdb_year'] = (amazon_df['imdb_year'].astype(str).str.extract(r'(\d{4})')[0]).astype('Int64')

amazon_df['imdb_year'] = pd.to_numeric(amazon_df['imdb_year'], errors='coerce')

In [29]:
amazon_df['imdb_rating'].isna().sum()

np.int64(48)

In [30]:
amazon_df = amazon_df.dropna(subset=['imdb_rating'])

In [31]:
amazon_df.head()

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type
0,Reacher,2022-02-04,TV-MA,8.0,291841.0,"Action, Crime, Drama",2022,series
1,The Terminal List,2022-07-01,TV-MA,7.9,127044.0,"Action, Drama, Thriller",2022,series
2,The Lord of the Rings: The Rings of Power,2022-09-01,TV-14,6.9,436113.0,"Action, Adventure, Drama",2022,series
3,The Devil's Hour,2022-10-28,TV-MA,7.6,32008.0,"Drama, Mystery, Thriller",2022,series
4,Citadel,2023-04-28,TV-14,6.2,37316.0,"Action, Drama, Thriller",2023,series

In [32]:
amazon_df.info()

<class 'pandas.DataFrame'>
Index: 80 entries, 0 to 125
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        80 non-null     str
 1   Premiere     80 non-null     str
 2   Rated        80 non-null     str
 3   imdb_rating  80 non-null     float64
 4   imdb_votes   80 non-null     float64
 5   imdb_genre   80 non-null     str
 6   imdb_year    80 non-null     Int64
 7   imdb_type    80 non-null     str
dtypes: Int64(1), float64(2), str(5)
memory usage: 5.7 KB

In [33]:
amazon_df.shape

(80, 8)

In [34]:
amazon_df.to_csv(
    "../data/series/processed/amazon_imdb.csv",
    index=False
)

## Adaptation Verification and Saving the Dataset

In [35]:
import pandas as pd

df = pd.read_csv("../data/series/processed/amazon_imdb_adaptations.csv")

df.head()

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type,is_book_adaptation,book_title,book_author
0,Reacher,04/02/2022,TV-MA,8.0,291841.0,"Action, Crime, Drama",2022,series,y,Jack Reacher series,Lee Child
1,The Terminal List,01/07/2022,TV-MA,7.9,127044.0,"Action, Drama, Thriller",2022,series,y,The Terminal List,Jack Carr
2,The Lord of the Rings: The Rings of Power,01/09/2022,TV-14,6.9,436113.0,"Action, Adventure, Drama",2022,series,y,The Lord of the Rings and related Middle-earth...,J. R. R. Tolkien
3,The Devil's Hour,28/10/2022,TV-MA,7.6,32008.0,"Drama, Mystery, Thriller",2022,series,n,NaN,NaN
4,Citadel,28/04/2023,TV-14,6.2,37316.0,"Action, Drama, Thriller",2023,series,n,NaN,NaN

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               80 non-null     str
 1   Premiere            80 non-null     str
 2   Rated               48 non-null     str
 3   imdb_rating         80 non-null     float64
 4   imdb_votes          80 non-null     float64
 5   imdb_genre          79 non-null     str
 6   imdb_year           80 non-null     int64
 7   imdb_type           80 non-null     str
 8   is_book_adaptation  80 non-null     str
 9   book_title          20 non-null     str
 10  book_author         20 non-null     str
dtypes: float64(2), int64(1), str(8)
memory usage: 7.0 KB

In [37]:
df.columns

Index(['Title', 'Premiere', 'Rated', 'imdb_rating', 'imdb_votes', 'imdb_genre',
       'imdb_year', 'imdb_type', 'is_book_adaptation', 'book_title',
       'book_author'],
      dtype='str')

In [38]:
df["is_book_adaptation"].value_counts()

is_book_adaptation
n    60
y    20
Name: count, dtype: int64

In [39]:
adaptations_df = df[df["is_book_adaptation"] == "y"].copy()

In [40]:
adaptations_df.shape

(20, 11)

In [41]:
adaptations_df[["book_title", "book_author"]].isnull().sum()

book_title     0
book_author    0
dtype: int64

In [42]:
adaptations_df["book_title"] = adaptations_df["book_title"].str.strip().str.lower()
adaptations_df["book_author"] = adaptations_df["book_author"].str.strip().str.lower()

In [43]:
adaptations_df[["book_title", "book_author"]].head(10)

                                           book_title            book_author
0                                 jack reacher series              lee child
1                                   the terminal list              jack carr
2   the lord of the rings and related middle-earth...       j. r. r. tolkien
6                                   alex cross series        james patterson
8                                       we were liars            e. lockhart
9                                renée ballard novels       michael connelly
10                         the terminal list universe              jack carr
11                                             malice        keigo higashino
13                                            56 days  catherine ryan howard
14                       young sherlock holmes series            andrew lane

In [44]:
import re

def clean_title(text):
    text = text.lower()
    text = re.sub(r"\(.*?\)", "", text)   # remove brackets content
    text = text.replace(",", " ")
    text = re.sub(r"\s+", " ", text)     # remove extra spaces
    return text.strip()

adaptations_df["book_title"] = adaptations_df["book_title"].apply(clean_title)

In [45]:
def to_search_key(text):
    text = text.lower()
    text = re.sub(r"(series|universe|novels|books)", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

adaptations_df["search_key"] = adaptations_df["book_title"].apply(to_search_key)

In [46]:
adaptations_df.head(10)

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type,is_book_adaptation,book_title,book_author,search_key
0,Reacher,04/02/2022,TV-MA,8.0,291841.0,"Action, Crime, Drama",2022,series,y,jack reacher series,lee child,jack reacher
1,The Terminal List,01/07/2022,TV-MA,7.9,127044.0,"Action, Drama, Thriller",2022,series,y,the terminal list,jack carr,the terminal list
2,The Lord of the Rings: The Rings of Power,01/09/2022,TV-14,6.9,436113.0,"Action, Adventure, Drama",2022,series,y,the lord of the rings and related middle-earth...,j. r. r. tolkien,the lord of the rings and related middle-earth...
6,Cross,14/11/2024,TV-MA,7.2,34967.0,"Action, Crime, Drama",2024,series,y,alex cross series,james patterson,alex cross
8,We Were Liars,18/06/2025,TV-14,6.8,15550.0,"Drama, Mystery, Romance",2025,series,y,we were liars,e. lockhart,we were liars
9,Ballard,09/07/2025,TV-14,7.5,22736.0,"Crime, Drama",2025,series,y,renée ballard novels,michael connelly,renée ballard
10,The Terminal List: Dark Wolf,27/08/2025,TV-MA,7.6,26656.0,"Action, Drama, Thriller",2025,series,y,the terminal list universe,jack carr,the terminal list
11,Malice,14/11/2025,R,6.5,30561.0,"Crime, Mystery, Thriller",1993,movie,y,malice,keigo higashino,malice
13,56 Days,18/02/2026,NaN,6.5,1393.0,"Crime, Drama, Mystery",2026,series,y,56 days,catherine ryan howard,56 days
14,Young Sherlock,04/03/2026,TV-14,7.5,24793.0,"Action, Adventure, Drama",2026,series,y,young sherlock holmes series,andrew lane,young sherlock holmes

In [47]:
adaptations_df.duplicated().sum()

np.int64(0)

In [48]:
adaptations_df.info()

<class 'pandas.DataFrame'>
Index: 20 entries, 0 to 60
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               20 non-null     str
 1   Premiere            20 non-null     str
 2   Rated               17 non-null     str
 3   imdb_rating         20 non-null     float64
 4   imdb_votes          20 non-null     float64
 5   imdb_genre          20 non-null     str
 6   imdb_year           20 non-null     int64
 7   imdb_type           20 non-null     str
 8   is_book_adaptation  20 non-null     str
 9   book_title          20 non-null     str
 10  book_author         20 non-null     str
 11  search_key          20 non-null     str
dtypes: float64(2), int64(1), str(9)
memory usage: 2.0 KB

In [49]:
mismatch_df = adaptations_df[pd.to_datetime(adaptations_df['Premiere'], dayfirst=True).dt.year != adaptations_df['imdb_year']]

print(len(mismatch_df))

3

In [50]:
mismatch_df['year_diff'] = (pd.to_datetime(mismatch_df['Premiere'], dayfirst=True).dt.year - mismatch_df['imdb_year']).abs()

print(mismatch_df['year_diff'].value_counts().sort_index())

year_diff
1     1
32    1
33    1
Name: count, dtype: int64

In [51]:
mismatch_df = mismatch_df.sort_values('year_diff', ascending=False)

mismatch_df.to_csv('../data/series/processed/amazon_year_mismatches.csv', index=False)

print(f"Saved {len(mismatch_df)} mismatches")

Saved 3 mismatches

In [52]:
mismatch_df = pd.read_csv('../data/series/processed/corrected_amazon_mismatches.csv')

print("Remove:", (mismatch_df['keep'].str.lower() == 'n').sum())
print("Update:", (mismatch_df['keep'].str.lower() == 'y').sum())

Remove: 1
Update: 2

In [53]:
titles_to_remove = mismatch_df.loc[mismatch_df['keep'].str.lower() == 'n','Title']

adaptations_df = adaptations_df[~adaptations_df['Title'].isin(titles_to_remove)].copy()

In [54]:
updates = mismatch_df[mismatch_df['keep'].str.lower() == 'y'].set_index('Title')

adaptations_df = adaptations_df.set_index('Title')

cols_to_update = [
    'Rated',
    'imdb_rating',
    'imdb_votes',
    'imdb_genre',
    'imdb_year',
    'imdb_type'
]

for col in cols_to_update:
    adaptations_df.loc[updates.index, col] = updates[col]

adaptations_df = adaptations_df.reset_index()

In [55]:
print("Final rows:", len(adaptations_df))

Final rows: 19

In [56]:
adaptations_df.to_csv("../data/series/final/amazon_series.csv", index=False)

# Netflix Series Data Collection

## Web Scraping Wikipedia Data

In [57]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_Netflix_original_programming"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

tables = pd.read_html(StringIO(html))

print(len(tables))

112

In [58]:
for i, table in enumerate(tables):
    print(f"\nTABLE {i}")
    print(table.head())

TABLE 0
             Title                         Genre           Premiere  \
0     Virgin River                Romantic drama   December 6, 2019
1      The Witcher                 Fantasy drama  December 20, 2019
2      Outer Banks           Coming-of-age drama     April 15, 2020
3  Sweet Magnolias                Romantic drama       May 19, 2020
4       Bridgerton  Alternate historical romance  December 25, 2020

                  Seasons    Runtime  \
0  7 seasons, 74 episodes  39–54 min
1  4 seasons, 32 episodes  47–67 min
2  4 seasons, 40 episodes  40–85 min
3  5 seasons, 50 episodes  43–54 min
4  4 seasons, 32 episodes  52–73 min

                                              Status
0                                         Renewed[1]
1         Final season due to premiere in 2026[2][3]
2  Final season due to premiere on August 20, 202...
3                                            Pending
4                         Renewed for seasons 5–6[6]

TABLE 1
                      Title                   Genre           Premiere  \
0            Emily in Paris            Comedy drama    October 2, 2020
1                 Wednesday           Comedy horror  November 23, 2022
2                      Beef  Comedy drama anthology      April 6, 2023
3                 XO, Kitty   Romantic comedy drama       May 18, 2023
4  Survival of the Thickest            Comedy drama      July 13, 2023

                  Seasons    Runtime  \
0  5 seasons, 50 episodes  24–46 min
1  2 seasons, 16 episodes  47–69 min
2  2 seasons, 18 episodes  30–54 min
3  3 seasons, 26 episodes  24–35 min
4  2 seasons, 16 episodes  24–28 min

                                              Status
0    Final season due to premiere in 2026[2][31][32]
1                                        Renewed[33]
2                                            Pending
3                                            Pending
4  Final season due to premiere on July 2, 2026[3...

TABLE 2
                        Title             Genre           Premiere  \
0                   One Piece  Action-adventure    August 31, 2023
1  Avatar: The Last Airbender           Fantasy  February 22, 2024
2                   Geek Girl        Teen drama       May 30, 2024
3           Blippi's Job Show       Educational      April 7, 2025

                  Seasons    Runtime  \
0  2 seasons, 16 episodes  49–66 min
1    1 season, 8 episodes  47–63 min
2   1 season, 10 episodes  28–37 min
3  2 seasons, 20 episodes  17–21 min

                                              Status
0               Season 3 due to premiere in 2027[51]
1  Season 2 due to premiere on June 25, 2026[52][...
2                                        Renewed[54]
3                                            Pending

TABLE 3
                                       Title                            Genre  \
0                           Blue Eye Samurai                           Action
1                              Devil May Cry              Dark fantasy action
2                           Long Story Short                           Comedy
3                              Haunted Hotel                    Horror comedy
4  Kurukshetra: The Great War of Mahabharata  Epic mythology action adventure

             Premiere                 Seasons    Runtime Language  \
0    November 3, 2023    1 season, 8 episodes  35–62 min  English
1       April 3, 2025  2 seasons, 16 episodes  21–39 min  English
2     August 22, 2025   1 season, 10 episodes     25 min  English
3  September 19, 2025   1 season, 10 episodes  24–25 min  English
4    October 10, 2025   1 season, 18 episodes  27–31 min    Hindi

                                    Status
0                              Renewed[55]
1             Renewed for final season[56]
2  Season 2 due to premiere in 2026[2][57]
3                              Renewed[58]
4                                  Pending

TABLE 4
                       Title                Genre           Premiere  \
0         Record of Ragnarok               Action      June 17, 2021
1          Pokémon Concierge  Stop-motion fantasy  December 28, 2023
2                  Leviathan    Alternate history      July 10, 2025
3         My Melody & Kuromi               Comedy      July 24, 2025
4  Splinter Cell: Deathwatch               Action   October 14, 2025

                  Seasons    Runtime  Language       Status
0  3 seasons, 42 episodes  23–26 min  Japanese      Pending
1    1 season, 8 episodes  14–22 min  Japanese      Pending
2   1 season, 12 episodes  22–29 min  Japanese      Pending
3   1 season, 12 episodes  11–17 min  Japanese      Pending
4    1 season, 8 episodes  20–27 min   English  Renewed[62]

TABLE 5
                Title                        Genre           Premiere  \
0         Trash Truck                    Preschool  November 10, 2020
1   Gabby's Dollhouse  Preschool adventure fantasy    January 5, 2021
2  The Creature Cases      Preschool action comedy     April 12, 2022
3      Cocomelon Lane            Preschool musical  November 17, 2023
4    Barbie Mysteries             Adventure comedy   November 1, 2024

                   Seasons    Runtime Language  \
0   2 seasons, 28 episodes  10–17 min  English
1  13 seasons, 86 episodes  23–30 min  English
2  7 chapters, 59 episodes  16–29 min  English
3   7 seasons, 28 episodes  17–34 min  English
4   2 seasons, 16 episodes  21–26 min  English

                                        Status
0                                  Renewed[63]
1  Renewed through episode 100 (final)[64][65]
2                                  Renewed[63]
3                                      Pending
4                                      Pending

TABLE 6
                 Title             Genre                Premiere  \
0             Roosters            Comedy       February 28, 2025
1     Football Parents            Comedy            May 16, 2025
2     Amsterdam Empire       Crime drama        October 30, 2025
3     Awaiting release  Awaiting release        Awaiting release
4  The Perfect Lie[69]    Crime thriller  September 10, 2026[70]

                  Seasons           Runtime            Status
0  2 seasons, 14 episodes         29–35 min           Pending
1    1 season, 6 episodes         27–32 min       Renewed[68]
2    1 season, 7 episodes         40–52 min           Pending
3        Awaiting release  Awaiting release  Awaiting release
4                     TBA               TBA           Pending

TABLE 7
              Title         Genre          Premiere                 Seasons  \
0             Lupin   Crime drama   January 8, 2021    3 parts, 17 episodes
1       Blood Coast   Crime drama  December 6, 2023  2 seasons, 12 episodes
2            Furies        Action     March 1, 2024  2 seasons, 14 episodes
3          The Cage  Sports drama  November 8, 2024    1 season, 5 episodes
4  Under a Dark Sun      Thriller      July 9, 2025    1 season, 6 episodes

     Runtime                                             Status
0  42–56 min  Part 4 due to premiere on October 23, 2026[71]...
1  44–57 min                                        Renewed[73]
2  39–52 min                                            Pending
3  42–65 min                                        Renewed[74]
4  41–57 min                                            Pending

TABLE 8
              Title             Genre            Premiere  \
0       The Empress  Historical drama  September 29, 2022
1            Crooks       Crime drama       April 4, 2024
2  Murder Mindfully       Dark comedy    October 31, 2024
3             Dudes            Comedy     October 2, 2025
4        Unfamiliar       Crime drama    February 5, 2026

                  Seasons    Runtime  \
0  2 seasons, 12 episodes  47–63 min
1  2 seasons, 14 episodes  39–66 min
2  2 seasons, 16 episodes  28–38 min
3    1 season, 8 episodes  33–38 min
4    1 season, 6 episodes  49–58 min

                                              Status
0  Final season due to premiere in late 2026[75][76]
1                                            Pending
2                                            Pending
3                                            Pending
4                                            Pending

TABLE 9
                     Title                  Genre           Premiere  \
0              Delhi Crime      Police procedural     March 22, 2019
1               Mismatched        Romantic comedy  November 20, 2020
2  Yeh Kaali Kaali Ankhein      Romantic thriller   January 14, 2022
3           Guns & Gulaabs  Crime comedy thriller    August 18, 2023
4         Maamla Legal Hai     Legal comedy drama      March 1, 2024

                  Seasons    Runtime  \
0  3 seasons, 18 episodes  36–64 min
1  3 seasons, 22 episodes  28–44 min
2  2 seasons, 14 episodes  31–51 min
3    1 season, 7 episodes  44–81 min
4  2 seasons, 16 episodes  27–42 min

                                         Status
0                                       Pending
1  Final season due to premiere in 2026[77][78]
2                                   Renewed[79]
3                                   Renewed[80]
4                                       Pending

TABLE 10
                          Title            Genre            Premiere  \
0  Ratu Ratu Queens: The Series     Comedy drama  September 12, 2025
1                Made with Love  Romantic comedy      April 15, 2026
2        Night Shift for Cuties           Comedy        June 4, 2026

                Seasons    Runtime   Status
0  1 season, 6 episodes  37–51 min  Pending
1  1 season, 8 episodes  30–37 min  Pending
2  1 season, 8 episodes  25–35 min  Pending

TABLE 11
         Title         Genre           Premiere                 Seasons  \
0    My Family         Drama  February 19, 2025  2 seasons, 12 episodes
1     Real Men        Comedy       May 21, 2025    1 season, 8 episodes
2    Riv4lries    Teen drama    October 1, 2025   1 season, 14 episodes
3  Motorvalley  Sports drama  February 10, 2026    1 season, 6 episodes

     Runtime       Status
0  37–51 min      Pending
1  27–37 min  Renewed[84]
2     35 min      Pending
3  42–49 min      Pending

TABLE 12
                   Title                       Genre           Premiere  \
0            Glass Heart                 Music drama      July 31, 2025
1    Romantics Anonymous             Romantic comedy   October 16, 2025
2  Last Samurai Standing            Historical drama  November 13, 2025
3           Sins of Kujo  Crime thriller/Legal drama      April 2, 2026
4       Straight to Hell          Biopic/Crime drama     April 27, 2026

                 Seasons    Runtime       Status
0  1 season, 10 episodes  33–54 min      Pending
1   1 season, 8 episodes  39–57 min      Pending
2   1 season, 6 episodes  47–58 min  Renewed[85]
3  1 season, 10 episodes  39–69 min      Pending
4   1 season, 9 episodes  46–65 min      Pending

TABLE 13
                     Title                              Genre  \
0       All of Us Are Dead  Zombie apocalypse horror thriller
1              Bloodhounds                       Action drama
2       Genie, Make a Wish            Romantic fantasy comedy
3  The Price of Confession                   Mystery thriller
4         Awaiting release                   Awaiting release

           Premiere                 Seasons           Runtime  \
0  January 28, 2022   1 season, 12 episodes         53–71 min
1      June 9, 2023  2 seasons, 15 episodes         49–75 min
2   October 3, 2025   1 season, 13 episodes         54–62 min
3  December 5, 2025   1 season, 12 episodes         46–60 min
4  Awaiting release        Awaiting release  Awaiting release

             Status
0   Renewed[88][89]
1           Pending
2           Pending
3           Pending
4  Awaiting release

TABLE 14
                        Title                            Genre  \
0             The Resurrected           Revenge crime thriller
1      Had I Not Seen the Sun  Coming-of age romantic thriller
2  Million-Follower Detective                   Crime thriller
3            Agent from Above                   Action fantasy

            Premiere               Seasons    Runtime   Status
0    October 9, 2025  1 season, 9 episodes  46–69 min  Pending
1  November 13, 2025  2 parts, 20 episodes  50–69 min  Pending
2  February 12, 2026  1 season, 8 episodes  43–50 min  Pending
3      April 2, 2026  1 season, 8 episodes  37–45 min  Pending

TABLE 15
                     Title        Genre           Premiere  \
0                     1670       Comedy  December 13, 2023
1        Go Ahead, Brother  Crime drama   October 30, 2024
2  The Mothers of Penguins        Drama  November 13, 2024

                  Seasons    Runtime                                    Status
0  2 seasons, 16 episodes  29–44 min  Season 3 due to premiere in 2026[94][95]
1    1 season, 6 episodes  52–62 min                               Renewed[96]
2    1 season, 6 episodes  43–58 min                               Renewed[97]

TABLE 16
                       Title                    Genre           Premiere  \
0              Criminal Code              Crime drama  November 14, 2023
1          Rulers of Fortune              Crime drama   October 29, 2025
2      Radioactive Emergency         Historical drama     March 18, 2026
3  Brazil 70: The Third Star  Historical sports drama       May 29, 2026
4           Awaiting release         Awaiting release   Awaiting release

                  Seasons           Runtime            Status
0  2 seasons, 16 episodes         47–63 min       Renewed[98]
1    1 season, 8 episodes         50–62 min           Pending
2    1 season, 5 episodes         53–65 min           Pending
3    1 season, 5 episodes         53–75 min           Pending
4        Awaiting release  Awaiting release  Awaiting release

TABLE 17
              Title        Genre           Premiere                 Seasons  \
0       Alpha Males       Comedy  December 30, 2022  5 seasons, 42 episodes
1   Community Squad       Comedy  February 17, 2023  2 seasons, 14 episodes
2         The Manny       Comedy  December 24, 2023  3 seasons, 26 episodes
3      Baby Bandito  Heist drama   January 31, 2024  2 seasons, 16 episodes
4  Gangs of Galicia  Crime drama      June 21, 2024  2 seasons, 13 episodes

     Runtime                         Status
0  30–40 min  Renewed for final season[101]
1  22–29 min                        Pending
2  30–41 min                        Pending
3  34–43 min                        Pending
4  40–56 min  Renewed for final season[102]

TABLE 18
                     Title         Genre            Premiere  \
0          The Åre Murders   Crime drama    February 6, 2025
1  Diary of a Ditched Girl         Drama  September 11, 2025
2            The New Force  Period drama     October 3, 2025

                Seasons    Runtime        Status
0  1 season, 5 episodes  35–57 min  Renewed[118]
1  1 season, 7 episodes  26–35 min       Pending
2  1 season, 6 episodes  37–43 min       Pending

TABLE 19
             Title            Genre            Premiere  \
0            Ethos            Drama   November 12, 2020
1        Graveyard            Drama       June 17, 2022
2     Another Self            Drama       July 28, 2022
3  Thank You, Next  Romantic comedy         May 9, 2024
4         Platonic           Comedy  September 18, 2025

                  Seasons     Runtime  \
0    1 season, 8 episodes   40–58 min
1  2 seasons, 12 episodes  48–116 min
2  2 seasons, 16 episodes   45–67 min
3  3 seasons, 24 episodes   29–57 min
4    1 season, 8 episodes   41–57 min

                                              Status
0              Season 2 due to premiere in 2026[119]
1  Season 3 due to premiere on August 28, 2026[12...
2  Season 3 due to premiere on June 24, 2026[120]...
3                                            Pending
4                                            Pending

TABLE 20
                Title         Genre            Premiere  \
0  Home for Christmas  Comedy drama    December 5, 2019
1    The Chestnut Man   Crime drama  September 29, 2021
2              Kohrra   Crime drama       July 15, 2023
3    How to Ruin Love        Comedy        May 31, 2024
4             Catalog  Comedy drama       July 17, 2025

                  Seasons    Runtime   Language   Status
0  3 seasons, 20 episodes  25–36 min  Norwegian  Pending
1  2 seasons, 12 episodes  43–59 min     Danish  Pending
2  2 seasons, 12 episodes  38–60 min    Punjabi  Pending
3   2 seasons, 7 episodes  43–50 min      Sotho  Pending
4    1 season, 8 episodes  50–64 min     Arabic  Pending

TABLE 21
                         Title     Subject           Premiere  \
0  Formula 1: Drive to Survive      Sports      March 8, 2019
1                   Full Swing      Sports  February 15, 2023
2      Missing: Dead or Alive?  True crime       May 10, 2023
3                  Quarterback      Sports      July 12, 2023
4                     Homicide  True crime     March 20, 2024

                  Seasons    Runtime Language  \
0  8 seasons, 78 episodes  27–52 min  English
1  4 seasons, 27 episodes  39–60 min  English
2   2 seasons, 8 episodes  31–67 min  English
3  2 seasons, 15 episodes  43–57 min  English
4  3 seasons, 15 episodes  42–65 min  English

                                           Status
0                                         Pending
1                                         Pending
2                                         Pending
3  Season 3 due to premiere on July 14, 2026[129]
4                                         Pending

TABLE 22
                             Title        Genre           Premiere  \
0                   Selling Sunset    Docu-soap     March 22, 2019
1                    Love Is Blind  Dating show  February 13, 2020
2            Love Is Blind: Brazil  Dating show    October 6, 2021
3  The Ultimatum: Marry or Move On  Dating show      April 6, 2022
4             Love on the Spectrum  Dating show       May 18, 2022

                    Seasons     Runtime    Language  \
0    9 seasons, 90 episodes   23–80 min     English
1  10 seasons, 135 episodes  31–104 min     English
2    5 seasons, 56 episodes   27–89 min  Portuguese
3    3 seasons, 30 episodes   35–63 min     English
4    4 seasons, 27 episodes   37–55 min     English

                                     Status
0                                   Pending
1                              Renewed[132]
2                                   Pending
3  Season 4 due to premiere in 2026[2][133]
4                              Renewed[134]

TABLE 23
                                               Title                   Genre  \
0  My Next Guest Needs No Introduction with David...               Interview
1                  Dinner Time Live with David Chang  Cooking show/Talk show
2                        The Great Indian Kapil Show               Talk show
3                 Everybody's Live with John Mulaney               Talk show
4                               The Rest Is Football        Sports talk show

           Premiere                 Seasons    Runtime Language  \
0  January 12, 2018  6 seasons, 29 episodes  41–58 min  English
1  January 25, 2024  3 seasons, 51 episodes  45–89 min  English
2    March 30, 2024  4 seasons, 53 episodes  38–79 min    Hindi
3    March 12, 2025   1 season, 12 episodes  57–68 min  English
4     June 10, 2026   1 season, 11 episodes  39–49 min  English

                                 Status
0                          Renewed[157]
1                               Pending
2  Season 5 due to premiere in 2026[77]
3                          Renewed[158]
4                               Ongoing

TABLE 24
                       Title                              Genre  \
0  Black Mirror (series 3–7)          Science fiction anthology
1       Inside (seasons 2–3)                Reality competition
2      Death Inc. (season 3)                             Comedy
3     Crime Scene (season 5)  Murder mystery reality television

In [59]:
for i, table in enumerate(tables):
    if "Title" in table.columns:
        print(f"Table {i}")
        print(table.columns.tolist())
        print()

Table 0
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 1
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 2
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 3
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 4
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 5
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 6
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 7
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 8
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 9
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 10
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 11
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 12
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 13
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 14
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 15
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 16
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 17
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 18
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 19
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Status']

Table 20
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 21
['Title', 'Subject', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 22
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 23
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 24
['Title', 'Genre', 'Previous network(s)', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 25
[('Title', 'Awaiting release'), ('Genre', 'Awaiting release'), ('Premiere', 'Awaiting release'), ('Runtime', 'Awaiting release'), ('Language', 'Awaiting release')]

Table 26
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Status']

Table 27
['Title', 'Genre', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Netflix exclusive region', 'Status']

Table 28
['Title', 'Genre', 'Partner/Country', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Netflix exclusive regions', 'Status']

Table 29
['Title', 'Genre', 'Previous network(s)', 'Premiere', 'Seasons', 'Runtime', 'Language', 'Netflix exclusive region', 'Status']

Table 30
['Title', 'Genre', 'Premiere']

Table 31
['Title', 'Genre', 'Premiere']

Table 32
['Title', 'Genre', 'Premiere', 'Language']

Table 33
['Title', 'Genre', 'Premiere']

Table 34
['Title', 'Genre', 'Language', 'Premiere']

Table 35
['Title', 'Genre', 'Premiere']

Table 36
['Title', 'Genre', 'Premiere']

Table 37
['Title', 'Genre', 'Premiere']

Table 38
['Title', 'Genre', 'Premiere']

Table 39
['Title', 'Genre', 'Premiere']

Table 40
['Title', 'Genre', 'Premiere']

Table 41
['Title', 'Genre', 'Premiere']

Table 42
['Title', 'Genre', 'Premiere']

Table 43
['Title', 'Genre', 'Premiere']

Table 44
['Title', 'Genre', 'Premiere']

Table 45
['Title', 'Genre', 'Premiere']

Table 46
['Title', 'Genre', 'Premiere', 'Language']

Table 47
['Title', 'Subject', 'Premiere', 'Language']

Table 48
['Title', 'Genre', 'Premiere', 'Language']

Table 49
['Title', 'Genre', 'Partner/Country', 'Premiere', 'Language']

Table 50
['Title', 'Genre', 'Prev. network(s)', 'Premiere', 'Language']

Table 51
['Title', 'Genre', 'Premiere', 'Language']

Table 52
['Title', 'Genre']

In [60]:
df = []

needed = ["Title", "Premiere"]

for table in tables:
    table.columns = [
        col[0] if isinstance(col, tuple) else col
        for col in table.columns
    ]

    if all(col in table.columns for col in needed):
        df.append(table[needed])

netflix_df = pd.concat(df, ignore_index=True)

netflix_df.drop_duplicates(subset=["Title"], inplace=True)

print(netflix_df.head())
print(netflix_df.shape)

             Title           Premiere
0     Virgin River   December 6, 2019
1      The Witcher  December 20, 2019
2      Outer Banks     April 15, 2020
3  Sweet Magnolias       May 19, 2020
4       Bridgerton  December 25, 2020
(532, 2)

In [61]:
netflix_df.info()

<class 'pandas.DataFrame'>
Index: 532 entries, 0 to 542
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     532 non-null    str
 1   Premiere  532 non-null    object
dtypes: object(1), str(1)
memory usage: 12.5+ KB

In [62]:
netflix_df.isna().sum()

Title       0
Premiere    0
dtype: int64

In [63]:
netflix_df = netflix_df.drop_duplicates()

In [64]:
netflix_df.shape

(532, 2)

In [65]:
netflix_df.sample(n=10, random_state=42)

                                                 Title         Premiere
6                                   The Lincoln Lawyer     May 13, 2022
499                                         #Love[317]         2026[77]
108                                        Delhi Crime   March 22, 2019
497                             Empress of Flames[316]             2026
459                                   Anaesthesia[293]              TBA
231  The Echoes of Survivors: Inside Korea's Tragedies  August 15, 2025
246                                      The Dinosaurs    March 6, 2026
444                           Beauty in the Beast[284]              TBA
358                          The God of the Woods[197]              TBA
74                                           Dandelion   April 16, 2026

In [66]:
netflix_df['Title'] = netflix_df['Title'].str.replace(r'\[\d+\]', '', regex=True).str.strip()
netflix_df['Premiere'] = netflix_df['Premiere'].str.replace(r'\[\d+\]', '', regex=True).str.strip()

In [67]:
netflix_df["Title"] = (netflix_df["Title"].str.replace(r"\[[a-z]\]", "", regex=True).str.strip())

In [68]:
netflix_df[netflix_df["Title"].str.contains(r"\[", regex=True, na=False)]

Empty DataFrame
Columns: [Title, Premiere]
Index: []

In [69]:
netflix_df.sample(n=10, random_state=42)

                                                 Title         Premiere
6                                   The Lincoln Lawyer     May 13, 2022
499                                              #Love             2026
108                                        Delhi Crime   March 22, 2019
497                                  Empress of Flames             2026
459                                        Anaesthesia              TBA
231  The Echoes of Survivors: Inside Korea's Tragedies  August 15, 2025
246                                      The Dinosaurs    March 6, 2026
444                                Beauty in the Beast              TBA
358                               The God of the Woods              TBA
74                                           Dandelion   April 16, 2026

In [70]:
netflix_df['Premiere'] = pd.to_datetime(netflix_df['Premiere'],errors='coerce')

In [71]:
cutoff_date = pd.Timestamp('2026-06-18')

In [72]:
premiered_df = netflix_df[(netflix_df['Premiere'] .notna()) & (netflix_df['Premiere'] < cutoff_date)].copy()

upcoming_tba_df = netflix_df[(netflix_df['Premiere'].isna()) | (netflix_df['Premiere'] >= cutoff_date)].copy()

In [73]:
premiered_df.to_csv('../data/series/raw/netflix_titles.csv', index=False)
upcoming_tba_df.to_csv('../data/series/raw/upcoming_netflix.csv', index=False)

In [74]:
print(f"Premiered titles: {len(premiered_df)}")
print(f"Upcoming/TBA titles: {len(upcoming_tba_df)}")

Premiered titles: 300
Upcoming/TBA titles: 232

## Retrieving IMDb Metadata

In [75]:
import pandas as pd
import requests

API_KEY = "adebd275"

def get_omdb_data(title):
    try:
        url = f"https://www.omdbapi.com/?t={title}&apikey={API_KEY}"

        data = requests.get(url).json()

        return pd.Series({
            "Rated": data.get("Rated"),
            "imdb_rating": data.get("imdbRating"),
            "imdb_votes": data.get("imdbVotes"),
            "imdb_genre": data.get("Genre"),
            "imdb_year": data.get("Year"),
            "imdb_type": data.get("Type")
        })

    except:
        return pd.Series()

In [76]:
netflix_df = pd.read_csv('../data/series/raw/netflix_titles.csv')

In [77]:
omdb_data = netflix_df["Title"].apply(get_omdb_data)

netflix_df = pd.concat([netflix_df, omdb_data], axis=1)

netflix_df.head()

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type
0,Virgin River,2019-12-06,TV-14,7.4,"57,217","Drama, Romance",2019–,series
1,The Witcher,2019-12-20,TV-MA,7.9,"618,310","Action, Adventure, Drama",2019–,series
2,Outer Banks,2020-04-15,TV-MA,7.5,"104,906","Action, Crime, Drama",2020–2026,series
3,Sweet Magnolias,2020-05-19,TV-14,7.3,"27,427","Drama, Romance",2020–,series
4,Bridgerton,2020-12-25,TV-MA,7.5,"219,043","Drama, Romance",2020–,series

In [78]:
netflix_df.shape

(300, 8)

In [79]:
netflix_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        300 non-null    str
 1   Premiere     300 non-null    str
 2   Rated        277 non-null    str
 3   imdb_rating  277 non-null    str
 4   imdb_votes   277 non-null    str
 5   imdb_genre   277 non-null    str
 6   imdb_year    277 non-null    str
 7   imdb_type    277 non-null    str
dtypes: str(8)
memory usage: 18.9 KB

In [80]:
netflix_df['imdb_votes'] = (netflix_df['imdb_votes'].astype(str).str.replace(',', '', regex=False))

In [81]:
netflix_df['imdb_rating'] = pd.to_numeric(netflix_df['imdb_rating'], errors='coerce')
netflix_df['imdb_votes'] = pd.to_numeric(netflix_df['imdb_votes'], errors='coerce')

In [82]:
netflix_df['imdb_year'] = (netflix_df['imdb_year'].astype(str).str.extract(r'(\d{4})')[0].astype('Int64'))

In [83]:
netflix_df['imdb_year'] = pd.to_numeric(netflix_df['imdb_year'], errors='coerce')

In [84]:
netflix_df = netflix_df.dropna(subset=['imdb_rating'])

In [85]:
netflix_df.info()

<class 'pandas.DataFrame'>
Index: 222 entries, 0 to 296
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        222 non-null    str
 1   Premiere     222 non-null    str
 2   Rated        222 non-null    str
 3   imdb_rating  222 non-null    float64
 4   imdb_votes   222 non-null    float64
 5   imdb_genre   222 non-null    str
 6   imdb_year    222 non-null    Int64
 7   imdb_type    222 non-null    str
dtypes: Int64(1), float64(2), str(5)
memory usage: 15.8 KB

In [ ]:
netflix_df.to_csv("../data/series/processed/netflix_imdb.csv",index=False)

## Adaptation Verification and Saving the Dataset

In [87]:
import pandas as pd

df = pd.read_csv("../data/series/processed/netflix_imdb_adaptations.csv")

df.head()

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type,is_book_adaptation,book_title,book_author
0,Virgin River,06/12/2019,TV-14,7.4,57217,"Drama, Romance",2019,series,y,Virgin River series,Robyn Carr
1,The Witcher,20/12/2019,TV-MA,7.9,618310,"Action, Adventure, Drama",2019,series,y,The Witcher series,Andrzej Sapkowski
2,Outer Banks,15/04/2020,TV-MA,7.5,104906,"Action, Crime, Drama",2020,series,n,NaN,NaN
3,Sweet Magnolias,19/05/2020,TV-14,7.3,27427,"Drama, Romance",2020,series,y,Sweet Magnolias series,Sherryl Woods
4,Bridgerton,25/12/2020,TV-MA,7.5,219043,"Drama, Romance",2020,series,y,Bridgerton series,Julia Quinn

In [88]:
df["is_book_adaptation"].value_counts()

is_book_adaptation
n    184
y     38
Name: count, dtype: int64

In [89]:
adaptations_df = df[df["is_book_adaptation"] == "y"].copy()

In [90]:
adaptations_df.shape

(38, 11)

In [91]:
adaptations_df[["book_title", "book_author"]].isnull().sum()

book_title     0
book_author    0
dtype: int64

In [92]:
adaptations_df["book_title"] = adaptations_df["book_title"].str.strip().str.lower()
adaptations_df["book_author"] = adaptations_df["book_author"].str.strip().str.lower()

In [93]:
adaptations_df[["book_title", "book_author"]].head(10)

                                           book_title        book_author
0                                 virgin river series         robyn carr
1                                  the witcher series  andrzej sapkowski
3                              sweet magnolias series      sherryl woods
4                                   bridgerton series        julia quinn
5                                   the brass verdict   michael connelly
6                                     the night agent      matthew quirk
9                        my life with the walter boys          ali novak
10  the three-body problem (remembrance of earth's...          liu cixin
14                               ransom canyon series        jodi thomas
15                                           forever…         judy blume

In [94]:
import re

def clean_title(text):
    text = text.lower()
    text = re.sub(r"\(.*?\)", "", text)   # remove brackets content
    text = text.replace(",", " ")
    text = re.sub(r"\s+", " ", text)     # remove extra spaces
    return text.strip()

adaptations_df["book_title"] = adaptations_df["book_title"].apply(clean_title)

In [95]:
def to_search_key(text):
    text = text.lower()
    text = re.sub(r"(series|universe|novels|books)", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

adaptations_df["search_key"] = adaptations_df["book_title"].apply(to_search_key)

In [96]:
adaptations_df.head(10)

,Title,Premiere,Rated,imdb_rating,imdb_votes,imdb_genre,imdb_year,imdb_type,is_book_adaptation,book_title,book_author,search_key
0,Virgin River,06/12/2019,TV-14,7.4,57217,"Drama, Romance",2019,series,y,virgin river series,robyn carr,virgin river
1,The Witcher,20/12/2019,TV-MA,7.9,618310,"Action, Adventure, Drama",2019,series,y,the witcher series,andrzej sapkowski,the witcher
3,Sweet Magnolias,19/05/2020,TV-14,7.3,27427,"Drama, Romance",2020,series,y,sweet magnolias series,sherryl woods,sweet magnolias
4,Bridgerton,25/12/2020,TV-MA,7.5,219043,"Drama, Romance",2020,series,y,bridgerton series,julia quinn,bridgerton
5,The Lincoln Lawyer,13/05/2022,R,7.3,266302,"Crime, Drama, Mystery",2011,movie,y,the brass verdict,michael connelly,the brass verdict
6,The Night Agent,23/03/2023,TV-MA,7.4,151290,"Action, Drama, Thriller",2023,series,y,the night agent,matthew quirk,the night agent
9,My Life with the Walter Boys,07/12/2023,TV-14,6.8,22962,"Drama, Romance",2023,series,y,my life with the walter boys,ali novak,my life with the walter boys
10,3 Body Problem,21/03/2024,TV-MA,7.5,177200,"Adventure, Drama, Fantasy",2024,series,y,the three-body problem,liu cixin,the three-body problem
14,Ransom Canyon,17/04/2025,TV-MA,6.8,9381,"Drama, Romance, Western",2025,series,y,ransom canyon series,jodi thomas,ransom canyon
15,Forever,08/05/2025,TV-PG,8.2,65147,"Crime, Drama, Fantasy",2014,series,y,forever…,judy blume,forever…

In [97]:
adaptations_df.duplicated().sum()

np.int64(0)

In [98]:
mismatch_df = adaptations_df[pd.to_datetime(adaptations_df['Premiere'], dayfirst=True).dt.year != adaptations_df['imdb_year']]

print(len(mismatch_df))

7

In [99]:
mismatch_df['year_diff'] = (pd.to_datetime(mismatch_df['Premiere'], dayfirst=True).dt.year - mismatch_df['imdb_year']).abs()

print(mismatch_df['year_diff'].value_counts().sort_index())

year_diff
2     1
7     1
11    3
22    1
24    1
Name: count, dtype: int64

In [100]:
mismatch_df = mismatch_df.sort_values('year_diff', ascending=False)

mismatch_df.to_csv('../data/series/processed/netflix_year_mismatches.csv', index=False)

print(f"Saved {len(mismatch_df)} mismatches")

Saved 7 mismatches

In [101]:
mismatch_df = pd.read_csv('../data/series/processed/corrected_netflix_mismatches.csv')

print("Remove:", (mismatch_df['keep'].str.lower() == 'n').sum())
print("Update:", (mismatch_df['keep'].str.lower() == 'y').sum())

Remove: 0
Update: 7

In [102]:
titles_to_remove = mismatch_df.loc[mismatch_df['keep'].str.lower() == 'n','Title']

adaptations_df = adaptations_df[~adaptations_df['Title'].isin(titles_to_remove)].copy()

In [103]:
updates = mismatch_df[mismatch_df['keep'].str.lower() == 'y'].set_index('Title')

adaptations_df = adaptations_df.set_index('Title')

cols_to_update = [
    'Rated',
    'imdb_rating',
    'imdb_votes',
    'imdb_genre',
    'imdb_year',
    'imdb_type'
]

for col in cols_to_update:
    adaptations_df.loc[updates.index, col] = updates[col]

adaptations_df = adaptations_df.reset_index()

In [104]:
print("Final rows:", len(adaptations_df))

Final rows: 38

In [105]:
adaptations_df.to_csv("../data/series/final/netflix_series.csv", index=False)